### ISSUE TITLE
First try to compute efficiency is not very good

### ISSUE THREAD

**Issue by francispoulin** [eth-cscs/ImplicitGlobalGrid.jl#21]
I have tried running one of the examples on 1, 2 and 4 gpus to reproduce some scaling results.  I started wtih 'diffusion3D_multigpu_CuArray_novis.jl` with a coarser grid to see how it does.  Below you will find my results.

For this weak-scaling problem I compute the efficiencies on 2 and 4 cores to be 57 and 35 percent respectively.  I realize this is much coarser but is this surprising?

I have ensured that the system does have CUDA-aware MPI so that would not be a problem, I don't think.

```
$ mpiexec -np 1 julia --project diffusion3D_multigpu_CuArrays_novis.jl 
Global grid: 32x32x32 (nprocs: 1, dims: 1x1x1)
Simulation time = 41.547354999

$ mpiexec -np 2 julia --project diffusion3D_multigpu_CuArrays_novis.jl 
Global grid: 62x32x32 (nprocs: 2, dims: 2x1x1)
Simulation time = Simulation time = 72.528739102
72.494481903
$ mpiexec -np 4 julia --project diffusion3D_multigpu_CuArrays_novis.jl 
Global grid: 62x62x32 (nprocs: 4, dims: 2x2x1)
Simulation time = Simulation time = Simulation time = Simulation time = 116.549162142
116.549022381
```

**Comment by luraess** [comment]
Thanks @francispoulin for your interest in ImplicitGlobalGrid!

The weak scaling timings you report are to be expected since:
- you are running a very small local problem size (32x32x32) -the ratio of boundary points over total grid points is large and communication time is no longer negligible- and;
- the `diffusion3D_multigpu_CuArray_novis.jl` does not implement the `@hide_communication` feature to overlap and hide MPI communication by inner domain grid points computations.

Since your question is not really an issue with the package but rather a usage question, could you please re-post it on Julia Discourse in the most appropriate section - maybe [Julia at scale](https://discourse.julialang.org/c/domain/parallel/) ? As such, @omlins or myself could further assist you and other folks can also benefit from the discussion.

**Comment by francispoulin** [comment]
Thank you @luraess for the response, and your insights.  I will happily close this issue and copy the discussion to Discourse.

**Comment by luraess** [comment]
Thanks @francispoulin. Follow up for the question on Discourse: https://discourse.julialang.org/t/poor-scaling-results-with-implicigglobalgrid-jl/65170
