### ISSUE TITLE
CPU Multithreading Question

### ISSUE THREAD

**Issue by ali-vaziri** [eth-cscs/ImplicitGlobalGrid.jl#67]
Hi,

If one runs the example provided [here](https://github.com/eth-cscs/ImplicitGlobalGrid.jl/blob/master/examples/diffusion3D_multicpu_novis.jl) for CPU, only one thread per rank will be used (?). This is based on my observation, and setting 'JULIA_NUM_THREADS=n' or using 'julia --threads n' did not change it. If that's the case, would the solution for using multiple MPI ranks and multithreading within each rank involve combining ParallelStencil and ImplicitGlobalGrid, as demonstrated in the example [here](https://arxiv.org/pdf/2211.15716.pdf)?

Thanks!

**Comment by luraess** [comment]
Hi @ali-vaziri, thanks for reaching out. Note that usage questions (as this one, compared to issues) should rather be posted on [Julia Discourse](https://discourse.julialang.org).

The example you are flagging indeed would use only a single thread per MPI rank. Changing the numbers of threads to run Julia with will most likely not have any impact since the vectorised code used here cannot leverage multi-threading as such. To enable multi-threading per MPI rank, you'd need to write the vectorised statement (using broadcasting here) as compute functions (or kernels) in a loop fashion where you then could decorate the outer loop with `Threads.@threads` to enable multi-threading. This could be achieved on a higher-level approach by using e.g. ParallelStencil.

I am closing this for now, but feel free to post on Discourse.
